apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: score-app
    env: qa
  name: score-app
  namespace: mlops
spec:
  replicas: 2 # Creating two PODs for our app
  selector:
    matchLabels:
      app: score-app
  template:
    metadata:
      labels:
        app: score-app
        env: qa
    spec:
      containers:
      - image: gcr.io/flaskml-312001/ml-k8s:latest # Docker image name, that we pushed to GCR
        name: ml-k8s    # POD name 
        ports:
        - containerPort: 5000
          protocol: TCP
